services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - api
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16-alpine3.20
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - api

networks:
  api: